version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - chat-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map cổng 3000 của máy bạn vào cổng 80 của container Nginx
    networks:
      - chat-network
    depends_on:
      - backend

networks:
  chat-network:
    driver: bridge
